# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqZVAPxMrrrD8HhMgvVgK7xuaRDpN-e9
"""

!pip install -q faiss-cpu sentence-transformers transformers torch

!pip install -q reportlab

from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

embedder = SentenceTransformer("all-MiniLM-L6-v2")

MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForCausalLM.from_pretrained(
    MODEL, torch_dtype=torch.float32, device_map="cpu"
)

llm = pipeline("text-generation", model=model, tokenizer=tokenizer,
               max_new_tokens=40, do_sample=False)

import json

with open("/content/triage_flowcharts_weighted.json") as f:
    FLOWCHARTS = json.load(f)

import faiss
import numpy as np

texts = []
for fc in FLOWCHARTS:
    t = fc["title"] + " " + " ".join(fc["entry_keywords"])
    texts.append(t)

vecs = embedder.encode(texts)
vecs = np.array(vecs).astype("float32")

index = faiss.IndexFlatL2(vecs.shape[1])
index.add(vecs)

print("FAISS index ready")

def select_flowchart_semantic(user_text):

    q = embedder.encode([user_text])
    q = np.array(q).astype("float32")

    _, I = index.search(q, 1)
    return FLOWCHARTS[I[0][0]]

YES = ["yes","haan","yeah","true","yep","sure","of course"]
NO  = ["no","nah","nope","false","not","never"]

def parse_fast(ans):
    t = ans.lower()
    if any(x in t for x in YES):
        return "yes"
    if any(x in t for x in NO):
        return "no"
    return "unknown"

def llm_parse(q,a):

    prompt = f"""
        You are a clinical language interpreter.

        Task:
        Decide if the patient's answer means YES or NO to the question.

        Rules:
        - "I don't think so" = NO
        - "probably not" = NO
        - "not really" = NO
        - "maybe" = UNKNOWN
        - If unclear, return UNKNOWN
        - DO NOT guess.
        - Return ONLY one word: YES, NO, or UNKNOWN.

        Question:
        {q}

        Patient answer:
        {a}

        Output:
        """

    out = llm(prompt)[0]["generated_text"].lower()

    if "yes" in out: return "yes"
    if "no" in out: return "no"

    return "unknown"

def smart_parse(q,a):

    r = parse_fast(a)
    if r!="unknown":
        return r,"fast"

    if len(a.split()) <= 2:
        return "unknown","fast"

    r2 = llm_parse(q,a)
    return r2,"llm"

from datetime import datetime

def run_flowchart(fc):

    trace = {
        "selected_flowchart":{
            "id":fc["id"],
            "title":fc["title"],
            "scenario":fc["scenario"]
        },
        "time": str(datetime.now()),
        "qa": [],
        "red_flag": None,
        "final": None
    }

    score = 0

    for qid,node in fc["nodes"].items():

        ans = input(node["question"]+"\n> ")

        res,method = smart_parse(node["question"],ans)

        step = {
            "qid":qid,
            "question":node["question"],
            "answer":ans,
            "parsed_as":res,
            "parse_method":method,
            "score_delta":0,
            "red_flag":False
        }

        if res=="yes":
            step["score_delta"]=node["yes_score"]
            score+=node["yes_score"]

            if node["yes_red_flag"]:
                step["red_flag"]=True
                trace["red_flag"]=step
                trace["qa"].append(step)
                trace["final"]=show_result(fc,999)
                return trace

        elif res=="no":
            step["score_delta"]=node["no_score"]
            score+=node["no_score"]

            if node["no_red_flag"]:
                step["red_flag"]=True
                trace["red_flag"]=step
                trace["qa"].append(step)
                trace["final"]=show_result(fc,999)
                return trace

        trace["qa"].append(step)

    trace["final"]=show_result(fc,score)
    return trace

def show_result(fc, score):

    for t in fc["scoring"]["thresholds"]:
        if score >= t["min_score"]:
              print("\n=== RESULT ===")
              print("Triage:", t["triage"])
              print("Action:", t["action"])
              print("Score:", score)
              return {
                    "triage": t["triage"],
                    "action": t["action"],
                    "score": score
                }

from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors

def generate_pdf(trace,filename="/content/triage_report.pdf"):


    doc = SimpleDocTemplate(filename,pagesize=A4)
    styles = getSampleStyleSheet()
    el=[]

    el.append(Paragraph("AI Triage Explainability Report",styles["Title"]))
    el.append(Spacer(1,12))

    fc = trace["selected_flowchart"]
    f  = trace["final"]

    el.append(Paragraph(f"<b>Flowchart:</b> {fc['title']} ({fc['scenario']})",styles["Normal"]))
    el.append(Paragraph(f"<b>Triage:</b> {f['triage']}",styles["Normal"]))
    el.append(Paragraph(f"<b>Action:</b> {f['action']}",styles["Normal"]))
    el.append(Paragraph(f"<b>Score:</b> {f['score']}",styles["Normal"]))
    el.append(Paragraph(f"<b>Time:</b> {trace['time']}",styles["Normal"]))
    el.append(Spacer(1,12))

    data=[["QID","Question","User Answer","Parsed","Method","Score"]]

    for q in trace["qa"]:
        data.append([
            q["qid"],q["question"],q["answer"],
            q["parsed_as"],q["parse_method"],q["score_delta"]
        ])

    table=Table(data,repeatRows=1)
    table.setStyle(TableStyle([
        ('GRID',(0,0),(-1,-1),1,colors.black),
        ('BACKGROUND',(0,0),(-1,0),colors.lightgrey)
    ]))

    el.append(table)

    if trace["red_flag"]:
        rf=trace["red_flag"]
        el.append(Spacer(1,12))
        el.append(Paragraph("RED FLAG DETECTED",styles["Heading2"]))
        el.append(Paragraph(rf["question"],styles["Normal"]))
        el.append(Paragraph(rf["answer"],styles["Normal"]))

    doc.build(el)
    return filename

def select_flowchart(user_text):
    q = embedder.encode([user_text])
    q = np.array(q).astype("float32")

    _, I = index.search(q,1)
    return FLOWCHARTS[I[0][0]]

text = input("Describe symptoms: ")

fc = select_flowchart(text)

trace = run_flowchart(fc)

pdf_path = generate_pdf(trace)
pdf_path